<?php

/**
 * @file
 * Hook implementations.
 */

use Drupal\profile_ext\Entity\Profile;

/**
 * Implements hook_ENTITY_TYPE_alter().
 *
 * Replaces class to use for profile.
 */
function profile_ext_entity_type_alter(array $entity_types): void {
  if (isset($entity_types['profile'])) {
    $definition = $entity_types['profile'];
    $definition->setClass(Profile::class);
  }
}
